### ISSUE TITLE
Complete config 

### ISSUE THREAD

**Issue by kehiy** [zurvan-lab/TimeTrace#49]
we need to write config like what we define in this:
- #38

**Comment by kehiy** [comment]
final basic config file:

```yml
name: TimeTraceExampleConfig

server:
  listen: localhost
  port: 7070

log:
  path: ./ttrace.log

users:
  name: root
  password: super_secret_password
  cmd:
    - * # all commands.


# Also you can use this for multiple users and limited commands
# users:
#   - name: root
#     pass_word: super_secret_password
#     cmd:
#       - * # all commands.
#   - name: developer
#     password: secret_password
#     cmd:
#       - GET
#       - PUSH
#       - DEL
```
